// Base de datos
const preguntas = {
    pregunta1: {
        pregunta: "¿En qué año nació Lionel Messi?",
        opcionA: "1985",
        opcionB: "1987",
        opcionC: "1989",
        opcionD: "1991",
        respuestaCorrecta: "1987",
    },
    pregunta2: {
        pregunta: "¿Cuál es el equipo de fútbol en el que Lionel Messi comenzó su carrera profesional?",
        opcionA: "Barcelona",
        opcionB: "Newell's Old Boys",
        opcionC: "River Plate",
        opcionD: "Boca Juniors",
        respuestaCorrecta: "Newell's Old Boys",
    },
    pregunta3: {
        pregunta: "¿Cuántas veces ha ganado Lionel Messi el premio Balón de Oro?",
        opcionA: "5",
        opcionB: "7",
        opcionC: "4",
        opcionD: "6",
        respuestaCorrecta: "7",
    },
    pregunta4: {
        pregunta: "¿En qué país nació Diego Maradona?",
        opcionA: "Argentina",
        opcionB: "Brasil",
        opcionC: "Uruguay",
        opcionD: "Paraguay",
        respuestaCorrecta: "Argentina",
    },
    pregunta5: {
        pregunta: "¿Cuál fue el año del famoso 'Gol del Siglo' de Diego Maradona?",
        opcionA: "1982",
        opcionB: "1986",
        opcionC: "1990",
        opcionD: "1994",
        respuestaCorrecta: "1986",
    },
    pregunta6: {
        pregunta: "¿En qué club europeo jugó Diego Maradona después de su paso por el Barcelona?",
        opcionA: "Nápoles",
        opcionB: "Milán",
        opcionC: "Real Madrid",
        opcionD: "Juventus",
        respuestaCorrecta: "Nápoles",
    },
    pregunta7: {
        pregunta: "¿Cuál es el récord de goles en una sola temporada de Lionel Messi con el Barcelona?",
        opcionA: "50",
        opcionB: "60",
        opcionC: "73",
        opcionD: "65",
        respuestaCorrecta: "73",
    },
    pregunta8: {
        pregunta: "¿En qué mundial Diego Maradona lideró a la selección argentina hacia la victoria?",
        opcionA: "México 1986",
        opcionB: "Italia 1990",
        opcionC: "España 1982",
        opcionD: "Francia 1998",
        respuestaCorrecta: "México 1986",
    },
    pregunta9: {
        pregunta: "¿Cuál es el número de camiseta que Lionel Messi suele usar en la selección argentina?",
        opcionA: "10",
        opcionB: "7",
        opcionC: "11",
        opcionD: "9",
        respuestaCorrecta: "10",
    },
    pregunta10: {
        pregunta: "¿En qué posición del campo de juego solía jugar Diego Maradona?",
        opcionA: "Delantero",
        opcionB: "Mediocampista",
        opcionC: "Defensor",
        opcionD: "Portero",
        respuestaCorrecta: "Mediocampista",
    },
    pregunta11: {
        pregunta: "¿Cuántas veces ha ganado Lionel Messi la Liga de Campeones de la UEFA con el Barcelona?",
        opcionA: "3",
        opcionB: "4",
        opcionC: "5",
        opcionD: "2",
        respuestaCorrecta: "4",
    },
    pregunta12: {
        pregunta: "¿En qué año Lionel Messi debutó en el primer equipo del Barcelona?",
        opcionA: "2003",
        opcionB: "2005",
        opcionC: "2007",
        opcionD: "2009",
        respuestaCorrecta: "2004",
    },
    pregunta13: {
        pregunta: "¿En qué club argentino comenzó su carrera profesional Diego Maradona?",
        opcionA: "Boca Juniors",
        opcionB: "Independiente",
        opcionC: "Argentinos Juniors",
        opcionD: "Racing Club",
        respuestaCorrecta: "Argentinos Juniors",
    },
    pregunta14: {
        pregunta: "¿Cuál es el récord de goles en un solo partido de Lionel Messi en la Liga española?",
        opcionA: "4",
        opcionB: "5",
        opcionC: "6",
        opcionD: "7",
        respuestaCorrecta: "5",
    },
    pregunta15: {
        pregunta: "¿En qué Mundial Diego Maradona fue capitán de la selección argentina?",
        opcionA: "Italia 1990",
        opcionB: "México 1986",
        opcionC: "España 1982",
        opcionD: "Francia 1998",
        respuestaCorrecta: "Italia 1990",
    },
    pregunta16: {
        pregunta: "¿En qué año se celebró la primera Copa Mundial de Fútbol en Argentina?",
        opcionA: "1930",
        opcionB: "1942",
        opcionC: "1950",
        opcionD: "1962",
        respuestaCorrecta: "1930",
    },
    pregunta17: {
        pregunta: "¿Quién es la figura emblemática del tango argentino conocido como 'El Zorzal'?",
        opcionA: "Carlos Gardel",
        opcionB: "Aníbal Troilo",
        opcionC: "Astor Piazzolla",
        opcionD: "Osvaldo Pugliese",
        respuestaCorrecta: "Carlos Gardel",
    },
    pregunta18: {
        pregunta: "¿Cuál es el equipo de fútbol más laureado de Argentina?",
        opcionA: "River Plate",
        opcionB: "Boca Juniors",
        opcionC: "Independiente",
        opcionD: "Racing Club",
        respuestaCorrecta: "Independiente",
    },
    pregunta19: {
        pregunta: "¿En qué año se realizó la primera transmisión de televisión en Argentina?",
        opcionA: "1950",
        opcionB: "1955",
        opcionC: "1960",
        opcionD: "1965",
        respuestaCorrecta: "1951",
    },
    pregunta20: {
        pregunta: "¿Quién es la escritora argentina ganadora del Premio Nobel de Literatura en 2010?",
        opcionA: "Jorge Luis Borges",
        opcionB: "Julio Cortázar",
        opcionC: "Adolfo Bioy Casares",
        opcionD: "César Aira",
        respuestaCorrecta: "Jorge Luis Borges",
    },
    pregunta21: {
        pregunta: "¿Cuál es el monumento más icónico de la ciudad de Buenos Aires?",
        opcionA: "Obelisco",
        opcionB: "Teatro Colón",
        opcionC: "Casa Rosada",
        opcionD: "Puente de la Mujer",
        respuestaCorrecta: "Obelisco",
    },
    pregunta22: {
        pregunta: "¿Quién fue el líder militar argentino durante la Guerra de las Malvinas en 1982?",
        opcionA: "Juan Domingo Perón",
        opcionB: "Leopoldo Galtieri",
        opcionC: "Raúl Alfonsín",
        opcionD: "Carlos Menem",
        respuestaCorrecta: "Leopoldo Galtieri",
    },
    pregunta23: {
        pregunta: "¿Cuál es el deporte nacional de Argentina?",
        opcionA: "Fútbol",
        opcionB: "Rugby",
        opcionC: "Polo",
        opcionD: "Hockey sobre césped",
        respuestaCorrecta: "Polo",
    },
    pregunta24: {
        pregunta: "¿Quién es la figura central del movimiento peronista en Argentina?",
        opcionA: "Eva Perón",
        opcionB: "Juan Domingo Perón",
        opcionC: "Néstor Kirchner",
        opcionD: "Cristina Fernández de Kirchner",
        respuestaCorrecta: "Juan Domingo Perón",
    },
    pregunta25: {
        pregunta: "¿Cuál es la bebida nacional de Argentina?",
        opcionA: "Mate",
        opcionB: "Vino",
        opcionC: "Cerveza",
        opcionD: "Fernet",
        respuestaCorrecta: "Mate",
    },
    pregunta26: {
        pregunta: "¿Qué famoso evento cultural se celebra anualmente en la ciudad de Córdoba?",
        opcionA: "Festival Internacional de Jazz",
        opcionB: "Feria del Libro",
        opcionC: "Festival Nacional de Folklore",
        opcionD: "Festival Internacional de Cine",
        respuestaCorrecta: "Festival Nacional de Folklore",
    },
    pregunta27: {
        pregunta: "¿En qué año se inauguró el Teatro Colón de Buenos Aires?",
        opcionA: "1885",
        opcionB: "1908",
        opcionC: "1923",
        opcionD: "1950",
        respuestaCorrecta: "1908",
    },
    pregunta28: {
        pregunta: "¿Cuál es la danza folklórica más representativa de Argentina?",
        opcionA: "Tango",
        opcionB: "Cueca",
        opcionC: "Zamba",
        opcionD: "Chacarera",
        respuestaCorrecta: "Zamba",
    },
    pregunta29: {
        pregunta: "¿Qué escritor argentino es conocido por su obra 'Ficciones'?",
        opcionA: "Julio Cortázar",
        opcionB: "Ernesto Sabato",
        opcionC: "Jorge Luis Borges",
        opcionD: "Adolfo Bioy Casares",
        respuestaCorrecta: "Jorge Luis Borges",
    },
    pregunta30: {
        pregunta: "¿Cuál es la montaña más alta de Argentina?",
        opcionA: "Monte Fitz Roy",
        opcionB: "Cerro Torre",
        opcionC: "Aconcagua",
        opcionD: "Monte Pissis",
        respuestaCorrecta: "Aconcagua",
    },
    pregunta31: {
        pregunta: "¿Quién fue la primera presidenta de Argentina?",
        opcionA: "Isabel Perón",
        opcionB: "Cristina Fernández de Kirchner",
        opcionC: "María Estela Martínez de Perón",
        opcionD: "Eva Perón",
        respuestaCorrecta: "Isabel Perón",
    },
    pregunta32: {
        pregunta: "¿Qué cantante argentino es conocido como 'El Rey del Rock en Español'?",
        opcionA: "Fito Páez",
        opcionB: "Charly García",
        opcionC: "Gustavo Cerati",
        opcionD: "Andrés Calamaro",
        respuestaCorrecta: "Andrés Calamaro",
    },
    pregunta33: {
        pregunta: "¿En qué año se estableció la independencia de Argentina?",
        opcionA: "1810",
        opcionB: "1820",
        opcionC: "1830",
        opcionD: "1840",
        respuestaCorrecta: "1816",
    },
    pregunta34: {
        pregunta: "¿Qué equipo de baloncesto argentino ganó la medalla de oro en los Juegos Olímpicos de Atenas 2004?",
        opcionA: "San Lorenzo",
        opcionB: "Estudiantes de La Plata",
        opcionC: "Boca Juniors",
        opcionD: "Seleccion Argentina",
        respuestaCorrecta: "Seleccion Argentina",
    },
    pregunta35: {
        pregunta: "¿Cuál es el arquitecto argentino que diseñó el Obelisco de Buenos Aires?",
        opcionA: "César Pelli",
        opcionB: "Le Corbusier",
        opcionC: "Francisco Salamone",
        opcionD: "Alberto Prebisch",
        respuestaCorrecta: "Alberto Prebisch",
    },
    pregunta36: {
        pregunta: "¿Qué importante evento literario se celebra en la ciudad de Buenos Aires?",
        opcionA: "Feria del Libro",
        opcionB: "Festival de Poesía",
        opcionC: "Encuentro de Escritores",
        opcionD: "Maratón de Lectura",
        respuestaCorrecta: "Feria del Libro",
    },
    pregunta37: {
        pregunta: "¿En qué año se fundó el Club Atlético Boca Juniors?",
        opcionA: "1901",
        opcionB: "1905",
        opcionC: "1910",
        opcionD: "1913",
        respuestaCorrecta: "1905",
    },
    pregunta38: {
        pregunta: "¿Quién fue el presidente argentino durante la Revolución de Mayo en 1810?",
        opcionA: "Mariano Moreno",
        opcionB: "Juan José Castelli",
        opcionC: "Manuel Belgrano",
        opcionD: "Cornelio Saavedra",
        respuestaCorrecta: "Cornelio Saavedra",
    },
    pregunta39: {
        pregunta: "¿Cuál es el equipo de rugby más destacado de Argentina?",
        opcionA: "Los Pumas",
        opcionB: "Jaguares",
        opcionC: "Los Cóndores",
        opcionD: "Los Gauchos",
        respuestaCorrecta: "Los Pumas",
    },
    pregunta40: {
        pregunta: "¿En qué año se celebró la independencia de Argentina?",
        opcionA: "1810",
        opcionB: "1816",
        opcionC: "1820",
        opcionD: "1824",
        respuestaCorrecta: "1816",
    },
    pregunta41: {
        pregunta: "¿Cuál es el escritor argentino autor de 'El túnel'?",
        opcionA: "Julio Cortázar",
        opcionB: "Adolfo Bioy Casares",
        opcionC: "Ernesto Sabato",
        opcionD: "Leopoldo Marechal",
        respuestaCorrecta: "Ernesto Sabato",
    },
    pregunta42: {
        pregunta: "¿Qué ciudad argentina es famosa por su Festival Internacional de Cine Independiente?",
        opcionA: "Rosario",
        opcionB: "Mendoza",
        opcionC: "Córdoba",
        opcionD: "Mar del Plata",
        respuestaCorrecta: "Mar del Plata",
    },
    pregunta43: {
        pregunta: "¿Quién fue el líder del movimiento revolucionario peronista conocido como 'Che'?",
        opcionA: "Che Guevara",
        opcionB: "Che Menem",
        opcionC: "Che Perón",
        opcionD: "Che Kirchner",
        respuestaCorrecta: "Che Guevara",
    },
    pregunta44: {
        pregunta: "¿Cuál es el río más importante de Argentina?",
        opcionA: "Río Paraná",
        opcionB: "Río Uruguay",
        opcionC: "Río Paraguay",
        opcionD: "Río Salado",
        respuestaCorrecta: "Río Paraná",
    },
    pregunta45: {
        pregunta: "¿Qué famoso evento musical se celebra anualmente en la ciudad de Buenos Aires?",
        opcionA: "Lollapalooza Argentina",
        opcionB: "Quilmes Rock",
        opcionC: "Cosquín Rock",
        opcionD: "Festival Internacional de Jazz",
        respuestaCorrecta: "Lollapalooza Argentina",
    },
    pregunta46: {
        pregunta: "¿Cuál es el club de fútbol más antiguo de Argentina?",
        opcionA: "Boca Juniors",
        opcionB: "River Plate",
        opcionC: "Independiente",
        opcionD: "Rosario Central",
        respuestaCorrecta: "Rosario Central",
    },
    pregunta47: {
        pregunta: "¿En qué año se celebró la primera edición del Rally Dakar en Argentina?",
        opcionA: "2005",
        opcionB: "2008",
        opcionC: "2010",
        opcionD: "2012",
        respuestaCorrecta: "2009",
    },
    pregunta48: {
        pregunta: "¿Cuál es el símbolo nacional de Argentina que representa la libertad?",
        opcionA: "Sol de Mayo",
        opcionB: "Cruz del Sur",
        opcionC: "Cóndor Andino",
        opcionD: "Yaguareté",
        respuestaCorrecta: "Sol de Mayo",
    },
    pregunta49: {
        pregunta: "¿Quién es el director de cine argentino ganador de dos premios Óscar por 'El secreto de sus ojos'?",
        opcionA: "Gastón Duprat",
        opcionB: "Pablo Trapero",
        opcionC: "Juan José Campanella",
        opcionD: "Lucrecia Martel",
        respuestaCorrecta: "Juan José Campanella",
    },
    pregunta50: {
        pregunta: "¿En qué año se inauguró el Metro de Buenos Aires?",
        opcionA: "1913",
        opcionB: "1925",
        opcionC: "1930",
        opcionD: "1940",
        respuestaCorrecta: "1913",
    },
    pregunta51: {
        pregunta: "¿Cuál es la provincia argentina conocida como 'La Tierra del Sol y del Buen Vino'?",
        opcionA: "Mendoza",
        opcionB: "Salta",
        opcionC: "San Juan",
        opcionD: "La Rioja",
        respuestaCorrecta: "Mendoza",
    },
    pregunta52: {
        pregunta: "¿Qué famoso líder político y revolucionario argentino participó en la Revolución Cubana?",
        opcionA: "Juan Domingo Perón",
        opcionB: "Che Guevara",
        opcionC: "Leopoldo Galtieri",
        opcionD: "Néstor Kirchner",
        respuestaCorrecta: "Che Guevara",
    },
    pregunta53: {
        pregunta: "¿En qué ciudad argentina se celebra el Festival Internacional de Tango?",
        opcionA: "Buenos Aires",
        opcionB: "Rosario",
        opcionC: "Córdoba",
        opcionD: "Mendoza",
        respuestaCorrecta: "Buenos Aires",
    },
    pregunta54: {
        pregunta: "¿Cuál es el escritor argentino autor de 'Rayuela'?",
        opcionA: "Jorge Luis Borges",
        opcionB: "Julio Cortázar",
        opcionC: "Adolfo Bioy Casares",
        opcionD: "Ernesto Sabato",
        respuestaCorrecta: "Julio Cortázar",
    },
    pregunta55: {
        pregunta: "¿En qué año se fundó el Club Atlético Independiente?",
        opcionA: "1890",
        opcionB: "1900",
        opcionC: "1910",
        opcionD: "1920",
        respuestaCorrecta: "1905",
    },
    pregunta56: {
        pregunta: "¿Quién es la escritora argentina autora de 'Cuentos de la Selva'?",
        opcionA: "Victoria Ocampo",
        opcionB: "Silvina Ocampo",
        opcionC: "Alfonsina Storni",
        opcionD: "Horacio Quiroga",
        respuestaCorrecta: "Horacio Quiroga",
    },
    pregunta57: {
        pregunta: "¿Cuál es el nombre del famoso estadio de fútbol ubicado en el barrio de La Boca?",
        opcionA: "Estadio Monumental",
        opcionB: "Estadio Libertadores de América",
        opcionC: "Estadio Kempes",
        opcionD: "La Bombonera",
        respuestaCorrecta: "La Bombonera",
    },
    pregunta58: {
        pregunta: "¿En qué año se llevó a cabo la Revolución de Mayo en Argentina?",
        opcionA: "1808",
        opcionB: "1810",
        opcionC: "1812",
        opcionD: "1814",
        respuestaCorrecta: "1810",
    },
    pregunta59: {
        pregunta: "¿Cuál es el apodo del equipo nacional argentino de rugby?",
        opcionA: "Los Pumas",
        opcionB: "Los Leones",
        opcionC: "Los Cóndores",
        opcionD: "Los Gauchos",
        respuestaCorrecta: "Los Pumas",
    },
    pregunta60: {
        pregunta: "¿Qué famoso personaje de la literatura argentina es conocido como 'Martín Fierro'?",
        opcionA: "Juan Moreira",
        opcionB: "Santos Vega",
        opcionC: "Juan Facundo Quiroga",
        opcionD: "José Hernández",
        respuestaCorrecta: "José Hernández",
    },
    pregunta61: {
        pregunta: "¿En qué año se inauguró el Teatro Nacional Cervantes en Buenos Aires?",
        opcionA: "1915",
        opcionB: "1920",
        opcionC: "1925",
        opcionD: "1930",
        respuestaCorrecta: "1921",
    },
    pregunta62: {
        pregunta: "¿Cuál es el plato típico argentino a base de carne asada a la parrilla?",
        opcionA: "Empanadas",
        opcionB: "Milanesa",
        opcionC: "Asado",
        opcionD: "Locro",
        respuestaCorrecta: "Asado",
    },
    pregunta63: {
        pregunta: "¿Quién fue el presidente argentino conocido como 'El Padre de la Patria'?",
        opcionA: "Mariano Moreno",
        opcionB: "Manuel Belgrano",
        opcionC: "Juan José Castelli",
        opcionD: "José de San Martín",
        respuestaCorrecta: "José de San Martín",
    },
    pregunta64: {
        pregunta: "¿En qué año se fundó la Academia Argentina de Letras?",
        opcionA: "1875",
        opcionB: "1883",
        opcionC: "1891",
        opcionD: "1900",
        respuestaCorrecta: "1875",
    },
    pregunta65: {
        pregunta: "¿Cuál es la región argentina conocida por sus vastas extensiones de llanuras?",
        opcionA: "Cuyo",
        opcionB: "Pampa",
        opcionC: "Patagonia",
        opcionD: "Noroeste",
        respuestaCorrecta: "Pampa",
    },
    pregunta66: {
        pregunta: "¿Qué famoso bandoneonista argentino es considerado el maestro del tango?",
        opcionA: "Aníbal Troilo",
        opcionB: "Astor Piazzolla",
        opcionC: "Carlos Gardel",
        opcionD: "Osvaldo Pugliese",
        respuestaCorrecta: "Aníbal Troilo",
    },
    pregunta67: {
        pregunta: "¿Cuál es la fecha de la independencia de Argentina?",
        opcionA: "9 de julio de 1810",
        opcionB: "20 de junio de 1820",
        opcionC: "25 de mayo de 1816",
        opcionD: "12 de octubre de 1492",
        respuestaCorrecta: "9 de julio de 1816",
    },
    pregunta68: {
        pregunta: "¿Quién es el arquitecto argentino famoso por su obra en la ciudad de Mar del Plata?",
        opcionA: "Le Corbusier",
        opcionB: "Francisco Salamone",
        opcionC: "César Pelli",
        opcionD: "Amancio Williams",
        respuestaCorrecta: "Francisco Salamone",
    },
    pregunta69: {
        pregunta: "¿En qué año se realizó la primera transmisión de radio en Argentina?",
        opcionA: "1910",
        opcionB: "1920",
        opcionC: "1930",
        opcionD: "1940",
        respuestaCorrecta: "1920",
    },
    pregunta70: {
        pregunta: "¿Quién fue el líder sindical argentino y ex presidente del país?",
        opcionA: "Hugo Moyano",
        opcionB: "Carlos Menem",
        opcionC: "Juan Domingo Perón",
        opcionD: "Néstor Kirchner",
        respuestaCorrecta: "Juan Domingo Perón",
    },
    pregunta71: {
        pregunta: "¿Cuál es el festival de rock más grande de Argentina?",
        opcionA: "Lollapalooza Argentina",
        opcionB: "Quilmes Rock",
        opcionC: "Cosquín Rock",
        opcionD: "Personal Fest",
        respuestaCorrecta: "Quilmes Rock",
    },
    pregunta72: {
        pregunta: "¿En qué año se llevó a cabo la Guerra de la Triple Alianza en la que participó Argentina?",
        opcionA: "1850-1852",
        opcionB: "1864-1870",
        opcionC: "1879-1884",
        opcionD: "1896-1900",
        respuestaCorrecta: "1864-1870",
    },
    pregunta73: {
        pregunta: "¿Cuál es la ciudad argentina conocida como 'La Ciudad de las Diagonales'?",
        opcionA: "Rosario",
        opcionB: "Mendoza",
        opcionC: "La Plata",
        opcionD: "Córdoba",
        respuestaCorrecta: "La Plata",
    },
    pregunta74: {
        pregunta: "¿Quién fue la primera mujer en ocupar la presidencia de Argentina?",
        opcionA: "Cristina Fernández de Kirchner",
        opcionB: "Isabel Perón",
        opcionC: "Eva Perón",
        opcionD: "Margarita Stolbizer",
        respuestaCorrecta: "Isabel Perón",
    },
    pregunta75: {
        pregunta: "¿En qué año se estableció la Academia Nacional de Bellas Artes en Argentina?",
        opcionA: "1895",
        opcionB: "1903",
        opcionC: "1911",
        opcionD: "1920",
        respuestaCorrecta: "1903",
    },
    pregunta76: {
        pregunta: "¿Cuál es el cóctel argentino a base de Fernet y cola?",
        opcionA: "Mate Fizz",
        opcionB: "Fernet Spritz",
        opcionC: "Fernet con Pomelo",
        opcionD: "Fernet con Coca",
        respuestaCorrecta: "Fernet con Coca",
    },
    pregunta77: {
        pregunta: "¿Quién fue el general argentino que lideró la expedición libertadora a Chile y Perú?",
        opcionA: "Juan Manuel de Rosas",
        opcionB: "José de San Martín",
        opcionC: "Mariano Moreno",
        opcionD: "Manuel Belgrano",
        respuestaCorrecta: "José de San Martín",
    },
    pregunta78: {
        pregunta: "¿En qué año se realizó la primera exhibición del cine en Argentina?",
        opcionA: "1896",
        opcionB: "1902",
        opcionC: "1908",
        opcionD: "1914",
        respuestaCorrecta: "1896",
    },
    pregunta79: {
        pregunta: "¿Cuál es la provincia argentina conocida por sus paisajes montañosos y la Ruta de los Siete Lagos?",
        opcionA: "Mendoza",
        opcionB: "Salta",
        opcionC: "Jujuy",
        opcionD: "Neuquén",
        respuestaCorrecta: "Neuquén",
    },
    pregunta80: {
        pregunta: "¿Qué famoso dramaturgo y escritor argentino escribió 'Esperando a Godot'?",
        opcionA: "Luis Alberto Spinetta",
        opcionB: "Federico García Lorca",
        opcionC: "Eugene O'Neill",
        opcionD: "Samuel Beckett",
        respuestaCorrecta: "Samuel Beckett",
    },
    pregunta81: {
        pregunta: "¿Cuál es la principal fiesta popular de Argentina que se celebra en febrero?",
        opcionA: "Carnaval",
        opcionB: "Fiesta de la Vendimia",
        opcionC: "Oktoberfest",
        opcionD: "Fiesta Nacional de la Manzana",
        respuestaCorrecta: "Carnaval",
    },
    pregunta82: {
        pregunta: "¿Quién fue la destacada escritora argentina ganadora del Premio Nobel de la Paz en 1976?",
        opcionA: "Victoria Ocampo",
        opcionB: "Alejandra Pizarnik",
        opcionC: "Gabriela Mistral",
        opcionD: "Adolfo Bioy Casares",
        respuestaCorrecta: "Gabriela Mistral",
    },
    pregunta83: {
        pregunta: "¿Cuál es el famoso glacial ubicado en la provincia de Santa Cruz?",
        opcionA: "Glaciar Perito Moreno",
        opcionB: "Glaciar Martial",
        opcionC: "Glaciar Upsala",
        opcionD: "Glaciar Viedma",
        respuestaCorrecta: "Glaciar Perito Moreno",
    },
    pregunta84: {
        pregunta: "¿Quién es considerado el padre del cuento argentino?",
        opcionA: "Jorge Luis Borges",
        opcionB: "Julio Cortázar",
        opcionC: "Adolfo Bioy Casares",
        opcionD: "Horacio Quiroga",
        respuestaCorrecta: "Horacio Quiroga",
    },
    pregunta85: {
        pregunta: "¿Cuál es la obra más conocida de Julio Cortázar?",
        opcionA: "Funes, el memorioso",
        opcionB: "Rayuela",
        opcionC: "Bestiario",
        opcionD: "Final del juego",
        respuestaCorrecta: "Rayuela",
    },
    pregunta86: {
        pregunta: "¿En qué año se estrenó la película argentina 'El secreto de sus ojos'?",
        opcionA: "2005",
        opcionB: "2009",
        opcionC: "2013",
        opcionD: "2017",
        respuestaCorrecta: "2009",
    },
    pregunta87: {
        pregunta: "¿Quién dirigió la película argentina 'Nueve reinas'?",
        opcionA: "Pablo Trapero",
        opcionB: "Juan José Campanella",
        opcionC: "Fabián Bielinsky",
        opcionD: "Lucrecia Martel",
        respuestaCorrecta: "Fabián Bielinsky",
    },
    pregunta88: {
        pregunta: "¿Cuál es el título de la novela más conocida de Ernesto Sabato?",
        opcionA: "Sobre héroes y tumbas",
        opcionB: "El túnel",
        opcionC: "La invención del amor",
        opcionD: "Cien años de soledad",
        respuestaCorrecta: "El túnel",
    },
    pregunta89: {
        pregunta: "¿En qué género literario se destaca la escritora argentina Silvina Ocampo?",
        opcionA: "Poesía",
        opcionB: "Teatro",
        opcionC: "Novela",
        opcionD: "Cuento",
        respuestaCorrecta: "Cuento",
    },
    pregunta90: {
        pregunta: "¿Quién es el autor de la novela 'Santa Evita'?",
        opcionA: "Tomás Eloy Martínez",
        opcionB: "Gabriel García Márquez",
        opcionC: "Isabel Allende",
        opcionD: "Alejandro Dolina",
        respuestaCorrecta: "Tomás Eloy Martínez",
    },
    pregunta91: {
        pregunta: "¿En qué año se publicó 'Martín Fierro' de José Hernández?",
        opcionA: "1872",
        opcionB: "1888",
        opcionC: "1896",
        opcionD: "1905",
        respuestaCorrecta: "1872",
    },
    pregunta92: {
        pregunta: "¿Cuál es la trama principal de la película 'El secreto de sus ojos'?",
        opcionA: "Un robo millonario",
        opcionB: "Un asesinato sin resolver",
        opcionC: "Una historia de amor imposible",
        opcionD: "Un viaje en el tiempo",
        respuestaCorrecta: "Un asesinato sin resolver",
    },
    pregunta93: {
        pregunta: "¿Qué escritor argentino recibió el Premio Nobel de Literatura en 2010?",
        opcionA: "Jorge Luis Borges",
        opcionB: "Julio Cortázar",
        opcionC: "Adolfo Bioy Casares",
        opcionD: "Mario Vargas Llosa",
        respuestaCorrecta: "Mario Vargas Llosa",
    },
    pregunta94: {
        pregunta: "¿En qué año se estrenó la película 'El secreto de sus ojos'?",
        opcionA: "2005",
        opcionB: "2009",
        opcionC: "2013",
        opcionD: "2017",
        respuestaCorrecta: "2009",
    },
    pregunta95: {
        pregunta: "¿Quién fue el director de cine argentino conocido como 'El Negro'?",
        opcionA: "Fernando Solanas",
        opcionB: "Lucrecia Martel",
        opcionC: "Juan José Campanella",
        opcionD: "Leopoldo Torre Nilsson",
        respuestaCorrecta: "Leopoldo Torre Nilsson",
    },
    pregunta96: {
        pregunta: "¿Cuál es la obra más destacada del dramaturgo argentino Roberto Arlt?",
        opcionA: "El juguete rabioso",
        opcionB: "Los siete locos",
        opcionC: "Trescientos millones",
        opcionD: "El amor brujo",
        respuestaCorrecta: "Los siete locos",
    },
    pregunta97: {
        pregunta: "¿En qué año se estrenó la película argentina 'La historia oficial'?",
        opcionA: "1980",
        opcionB: "1985",
        opcionC: "1990",
        opcionD: "1995",
        respuestaCorrecta: "1985",
    },
    pregunta98: {
        pregunta: "¿Quién es el autor de la novela 'El túnel'?",
        opcionA: "Julio Cortázar",
        opcionB: "Ernesto Sabato",
        opcionC: "Alberto Manguel",
        opcionD: "César Aira",
        respuestaCorrecta: "Ernesto Sabato",
    },
    pregunta99: {
        pregunta: "¿Cuál es el título de la obra más conocida de Alfonsina Storni?",
        opcionA: "La insumisa",
        opcionB: "Mundo de siete pozos",
        opcionC: "La tierra de nadie",
        opcionD: "La luna de enfrente",
        respuestaCorrecta: "La insumisa",
    },
    pregunta100: {
        pregunta: "¿En qué género se destaca la escritora argentina Samanta Schweblin?",
        opcionA: "Poesía",
        opcionB: "Novela negra",
        opcionC: "Ciencia ficción",
        opcionD: "Cuento",
        respuestaCorrecta: "Novela negra",
    },
};
