// Base de datos
const preguntas = {
    pregunta1: {
        pregunta: "¿En qué año nació Lionel Messi?",
        opcionA: "1985",
        opcionB: "1987",
        opcionC: "1989",
        opcionD: "1991",
        respuestaCorrecta: "1987",
    },
    pregunta2: {
        pregunta: "¿Cuál es el equipo de fútbol en el que Lionel Messi comenzó su carrera?",
        opcionA: "Barcelona",
        opcionB: "Newell's Old Boys",
        opcionC: "River Plate",
        opcionD: "Boca Juniors",
        respuestaCorrecta: "Newell's Old Boys",
    },
    pregunta3: {
        pregunta: "¿Cuántas veces ha ganado Lionel Messi el premio Balón de Oro?",
        opcionA: "8",
        opcionB: "7",
        opcionC: "4",
        opcionD: "6",
        respuestaCorrecta: "8",
    },
    pregunta4: {
        pregunta: "¿En qué país nació Diego Maradona?",
        opcionA: "Argentina",
        opcionB: "Brasil",
        opcionC: "Uruguay",
        opcionD: "Paraguay",
        respuestaCorrecta: "Argentina",
    },
    pregunta5: {
        pregunta: "¿En qué año fue el famoso 'Gol del Siglo' de Diego Maradona?",
        opcionA: "1982",
        opcionB: "1986",
        opcionC: "1990",
        opcionD: "1994",
        respuestaCorrecta: "1986",
    },
    pregunta6: {
        pregunta: "¿En qué club europeo jugó Diego Maradona después de su paso por el Barcelona?",
        opcionA: "Nápoles",
        opcionB: "Milán",
        opcionC: "Real Madrid",
        opcionD: "Juventus",
        respuestaCorrecta: "Nápoles",
    },
    pregunta7: {
        pregunta: "¿Cuál es el récord de goles en una sola liga de Lionel Messi con el Barcelona?",
        opcionA: "50",
        opcionB: "60",
        opcionC: "73",
        opcionD: "65",
        respuestaCorrecta: "50",
    },
    pregunta8: {
        pregunta: "¿En qué mundial Diego Maradona lideró a la selección argentina hacia la victoria?",
        opcionA: "México 1986",
        opcionB: "Italia 1990",
        opcionC: "España 1982",
        opcionD: "Francia 1998",
        respuestaCorrecta: "México 1986",
    },
    pregunta9: {
        pregunta: "¿Cuál es el número de camiseta que Lionel Messi suele usar en la selección argentina?",
        opcionA: "10",
        opcionB: "7",
        opcionC: "11",
        opcionD: "9",
        respuestaCorrecta: "10",
    },
    pregunta10: {
        pregunta: "¿En qué posición del campo de juego solía jugar Diego Maradona?",
        opcionA: "Delantero",
        opcionB: "Mediocampista ofensivo",
        opcionC: "Defensor",
        opcionD: "Portero",
        respuestaCorrecta: "Mediocampista ofensivo",
    },
    pregunta11: {
        pregunta: "¿Cuántas veces ha ganado Lionel Messi la Liga de Campeones de la UEFA con el Barcelona?",
        opcionA: "3",
        opcionB: "4",
        opcionC: "5",
        opcionD: "2",
        respuestaCorrecta: "4",
    },
    pregunta12: {
        pregunta: "¿En qué año Lionel Messi debutó en el primer equipo del Barcelona?",
        opcionA: "2004",
        opcionB: "2005",
        opcionC: "2007",
        opcionD: "2009",
        respuestaCorrecta: "2004",
    },
    pregunta13: {
        pregunta: "¿En qué club argentino comenzó su carrera profesional Diego Maradona?",
        opcionA: "Boca Juniors",
        opcionB: "Independiente",
        opcionC: "Argentinos Juniors",
        opcionD: "Racing Club",
        respuestaCorrecta: "Argentinos Juniors",
    },
    pregunta14: {
        pregunta: "¿Cuál es el récord de goles en un solo partido de Lionel Messi en la Liga española?",
        opcionA: "4",
        opcionB: "5",
        opcionC: "6",
        opcionD: "7",
        respuestaCorrecta: "5",
    },
    pregunta15: {
        pregunta: "¿En qué Mundial Diego Maradona fue capitán de la selección argentina?",
        opcionA: "Italia 1990",
        opcionB: "Brasil 2014",
        opcionC: "España 1982",
        opcionD: "Francia 1998",
        respuestaCorrecta: "Italia 1990",
    },
};
