// Base de datos
const preguntas = {
    pregunta1: {
        pregunta: "¿En qué año se fundó la Organización de las Naciones Unidas (ONU)?",
        opcionA: "1945",
        opcionB: "1955",
        opcionC: "1965",
        opcionD: "1975",
        respuestaCorrecta: "1945",
    },
    pregunta2: {
        pregunta: "¿Cuál es el planeta más grande del sistema solar?",
        opcionA: "Júpiter",
        opcionB: "Saturno",
        opcionC: "Neptuno",
        opcionD: "Urano",
        respuestaCorrecta: "Júpiter",
    },
    pregunta3: {
        pregunta: "¿Cuál es la capital de Australia?",
        opcionA: "Sídney",
        opcionB: "Melbourne",
        opcionC: "Canberra",
        opcionD: "Brisbane",
        respuestaCorrecta: "Canberra",
    },
    pregunta4: {
        pregunta: "¿Cuál es la lengua oficial de Brasil?",
        opcionA: "Español",
        opcionB: "Portugués",
        opcionC: "Francés",
        opcionD: "Italiano",
        respuestaCorrecta: "Portugués",
    },
    pregunta5: {
        pregunta: "¿Qué elemento químico tiene el símbolo 'O' en la tabla periódica?",
        opcionA: "Oxígeno",
        opcionB: "Oro",
        opcionC: "Plata",
        opcionD: "Hierro",
        respuestaCorrecta: "Oxígeno",
    },
    pregunta6: {
        pregunta: "¿Cuál es la montaña más alta del mundo?",
        opcionA: "Mont Blanc",
        opcionB: "Kilimanjaro",
        opcionC: "Everest",
        opcionD: "Aconcagua",
        respuestaCorrecta: "Everest",
    },
    pregunta7: {
        pregunta: "¿Quién escribió la obra 'Romeo y Julieta'?",
        opcionA: "William Shakespeare",
        opcionB: "Charles Dickens",
        opcionC: "Jane Austen",
        opcionD: "Mark Twain",
        respuestaCorrecta: "William Shakespeare",
    },
    pregunta8: {
        pregunta: "¿En qué año se llevó a cabo la independencia de Estados Unidos?",
        opcionA: "1776",
        opcionB: "1789",
        opcionC: "1800",
        opcionD: "1825",
        respuestaCorrecta: "1776",
    },
    pregunta9: {
        pregunta: "¿Cuál es la capital de Japón?",
        opcionA: "Pekín",
        opcionB: "Seúl",
        opcionC: "Tokio",
        opcionD: "Bangkok",
        respuestaCorrecta: "Tokio",
    },
    pregunta10: {
        pregunta: "¿Cuál es la raíz cuadrada de 144?",
        opcionA: "10",
        opcionB: "12",
        opcionC: "14",
        opcionD: "16",
        respuestaCorrecta: "12",
    },
    pregunta11: {
        pregunta: "¿Cuál es el océano más grande del mundo?",
        opcionA: "Océano Atlántico",
        opcionB: "Océano Índico",
        opcionC: "Océano Pacífico",
        opcionD: "Océano Ártico",
        respuestaCorrecta: "Océano Pacífico",
    },
    pregunta12: {
        pregunta: "¿Quién pintó la Mona Lisa?",
        opcionA: "Pablo Picasso",
        opcionB: "Vincent van Gogh",
        opcionC: "Leonardo da Vinci",
        opcionD: "Claude Monet",
        respuestaCorrecta: "Leonardo da Vinci",
    },
    pregunta13: {
        pregunta: "¿Cuál es el animal terrestre más grande del mundo?",
        opcionA: "Elefante africano",
        opcionB: "Ballena azul",
        opcionC: "Jirafa",
        opcionD: "Rinoceronte blanco",
        respuestaCorrecta: "Ballena azul",
    },
    pregunta14: {
        pregunta: "¿En qué país se encuentra la Gran Muralla China?",
        opcionA: "India",
        opcionB: "Rusia",
        opcionC: "China",
        opcionD: "Japón",
        respuestaCorrecta: "China",
    },
    pregunta15: {
        pregunta: "¿Cuál es la capital de Francia?",
        opcionA: "Roma",
        opcionB: "París",
        opcionC: "Madrid",
        opcionD: "Berlín",
        respuestaCorrecta: "París",
    },
};
